[project]
name = "shandong-sentencing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pycnnum>=2.1.1",
    "sentence-transformers>=5.1.0",
]
